---
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE,message=FALSE, cache=FALSE)
```

```{r lang, include=FALSE}
PL <- FALSE
```

```{r setup, include=FALSE}
suppressWarnings(suppressPackageStartupMessages(library(deSolve)))
suppressWarnings(suppressPackageStartupMessages(library(RColorBrewer)))
suppressWarnings(suppressPackageStartupMessages(library(lubridate)))
suppressWarnings(suppressPackageStartupMessages(library(bbmle)))
suppressWarnings(suppressPackageStartupMessages(library(reshape2)))
suppressWarnings(suppressPackageStartupMessages(library(ggplot2)))
suppressWarnings(suppressPackageStartupMessages(library(cowplot)))
suppressWarnings(suppressPackageStartupMessages(library(mvtnorm)))
theme_set(theme_grey())
```

```{r data, include=FALSE}
reported <- read.csv("../../data/poland_covid_epidemic.csv")
reported <- reported[-1,]
reported[, 1] <- ymd(reported[, 1])
date.of.the.first.case <- reported$date[which(reported$cum.cases==1)[1]]
date.of.the.last.entry <- reported$date[nrow(reported)]
date.of.gov.restrictions <- ymd(20200314)
no.bootstraps <- 1000
```

```{r functions, include=FALSE}
# The model
model <- function(t, x, parms) {
  with(as.list(c(parms, x)), {
    gamma <- a*b/(a+b)
    beta <- R_0*gamma/popsize*(1+f*a/b)/(1+lambda*f*a/b)
    if(t > (seed + control)) beta <- kappa*R_0*gamma/popsize*(1+f*a/b)/(1+lambda*f*a/b)
    # if(t < (seed + control)){
    #   beta <- R_0*gamma/popsize*(1+f*a/b)/(1+lambda*f*a/b)
    # } else{
    #   beta <- kappa*R_0*gamma/popsize*(1+f*a/b)/(1+lambda*f*a/b)
    # }
    dS <- -beta*(IA+lambda*IS)*S
    dE <- beta*(IA+lambda*IS)*S - sigma*E
    dIA <- sigma*E - (1+f*a/b)*gamma*IA
    dIS <- f*a*IA - b*IS
    dQ <- q*b*IS - omega1*Q
    dH <- epsilon1*omega1*Q - omega2*H
    dV <- epsilon2*omega2*H - omega3*V
    dD <- epsilon3*omega3*V
    dR <- (1-f)*gamma*IA + (1-q)*b*IS + (1-epsilon1)*omega1*Q + (1-epsilon2)*omega2*H + (1-epsilon3)*omega3*V
    der <- c(dS, dE, dIA, dIS, dQ, dH, dV, dD, dR)
    list(der)
  })
}

# Maximum likelihood calculation; to be fed into mle2()
nll <- function(seed, R_0, sigma, a, b, f, q, omega1, omega2, omega3, epsilon1, epsilon2, epsilon3, lambda, control, kappa) {
  pars <- c(seed = seed, R_0 = R_0, sigma = sigma, a = a, b = b, f = f, q = q, 
            omega1 = omega1, omega2 = omega2, omega3 = omega3, epsilon1 = epsilon1, 
            epsilon2 = epsilon2, epsilon3 = epsilon3, lambda = lambda, control = control, kappa = kappa)
  pars <- trans(pars)
  times <- c(0, pars["seed"] + date - min(date))
  times <- c(times, max(times + 1))
  simulation <- as.data.frame(ode(inits, times, model, pars))
  simulation <- simulation[-1, ]
  ll <- sum(dpois(inc.deaths, diff(simulation$D), log = TRUE))
  return(-ll)
}

# Parameter transformation
trans <- function(pars) {
  pars["R_0"] <- exp(pars["R_0"])
  pars["seed"] <- exp(pars["seed"])
  pars["kappa"] <- plogis(pars["kappa"])
  return(pars)
}

date2polish <- function(date, return.only.month = FALSE){
  month.names <- 1:12
  test <- is.Date(date)
  out <- NULL
  if(test){
    get.day <- day(date)
    get.month <- month(date)
    out <- sprintf("%d/%.2d", get.day, month.names[get.month])
    if(return.only.month) out <- sprintf("%.2d", month.names[get.month])
  } else{
    cat("Must be in lubridate format! Returning NULL...")
  }
  return(out)
}

# Produce simualtions starting from the date of the first reported case
sim.from.first.case <- function(input.parms, max.time, initial.at.seed){
  times.from.seed.to.first <- c(0, input.parms["seed"])
  sim.from.seed.to.first <- as.data.frame(ode(initial.at.seed, times.from.seed.to.first, model, input.parms))
  initial.at.first.case <- as.numeric(sim.from.seed.to.first[2, 2:ncol(sim.from.seed.to.first)])
  names(initial.at.first.case) <- names(initial.at.seed)
  times.from.first.to.max <- 0:max.time
  input.parms["seed"] <- 0
  sim.from.first.to.max <- as.data.frame(ode(initial.at.first.case, times.from.first.to.max, model, input.parms))
  sim.from.first.to.max$time <- date.of.the.first.case + sim.from.first.to.max$time
  return(sim.from.first.to.max)  
}

```


```{r main, include=FALSE}
##################
## 1. Define model
##################

popsize <- 38386000
times <- 0:200			
inits <- c(S = popsize - 1,
           E = 0,
           IA = 1,
           IS = 0,
           Q = 0,
           H = 0,
           V = 0,
           D = 0,
           R = 0)
fixed <- c(sigma = 1/4.6,
           a = 1/0.5,
           b = 1/1.4,
           f = 0.8, # 20% patients are completely asymptomatic based on [1]
           q = 2/3,
           omega1 = 1/3.6,
           omega2 = 1/8,
           omega3 = 1/8,
           epsilon1 = 0.066, 
           epsilon2 = 0.3, # 30% of hospitalised patients require critical care [1]
           epsilon3 = 0.57, # IFR of 0.9% based on [1]
           lambda = 2,
           control = as.numeric(date.of.gov.restrictions - date.of.the.first.case)) # Lockdown 
free <- c(R_0 = log(3.0),
          seed = log(30),
          kappa = qlogis(0.9))

########################
## 2. Fit model to data
########################

fit <- mle2(nll, start = as.list(free), fixed = as.list(fixed), method = "Nelder-Mead", data = reported)
fit.parms <- trans(coef(fit))

####################################################
## 3. Estimate how R_t has been changing over time
####################################################

Rt.df <- NULL
start.day <- 12
end.day <- as.numeric(date.of.the.last.entry - date.of.gov.restrictions)
# end.day <- 19
for(index in start.day:end.day){
  cat(index)
  last.day <- date.of.gov.restrictions + index
  reported.retrospective <- reported[1:which(reported$date == last.day),]
  this.fit <- mle2(nll, start = as.list(free), fixed = as.list(fixed), method = "Nelder-Mead", data = reported.retrospective)
  this.fit.parms <- trans(coef(this.fit))
  this.fit.means <- coef(this.fit, exclude.fixed = TRUE)
  this.fit.vcov <- vcov(this.fit)
  this.sim.coefs <- data.frame(rmvnorm(no.bootstraps, mean = this.fit.means, sigma = this.fit.vcov))
  Rt.ci <- quantile(exp(this.sim.coefs$R_0)*plogis(this.sim.coefs$kappa), probs = c(0.025,0.975))
  this.Rt.df <- data.frame(time = reported.retrospective$date[nrow(reported.retrospective)],
                           Rt = as.numeric(this.fit.parms["R_0"]*this.fit.parms["kappa"]),
                           Rt.min = as.numeric(Rt.ci[1]), Rt.max = as.numeric(Rt.ci[2]))
  Rt.df <- rbind(Rt.df, this.Rt.df)
}

#######################################
## 4. Project best fit into the future
#######################################

fit.means <- coef(fit, exclude.fixed = TRUE)
fit.vcov <- vcov(fit)
sim.coefs <- data.frame(rmvnorm(no.bootstraps, mean = fit.means, sigma = fit.vcov))

R0.estim <- c(as.numeric(fit.parms["R_0"]), quantile(exp(sim.coefs$R_0), probs = c(0.025, 0.975)))
R.estim <- c(as.numeric(fit.parms["R_0"])*as.numeric(fit.parms["kappa"]), quantile(exp(sim.coefs$R_0)*plogis(sim.coefs$kappa), probs = c(0.025, 0.975)))
Kappa.estim <- c(as.numeric(fit.parms["kappa"]), quantile(plogis(sim.coefs$kappa), probs = c(0.025, 0.975)))
seed.estim <- c(as.numeric(fit.parms["seed"]), quantile(exp(sim.coefs$seed), probs = c(0.025, 0.975)))
tseed.estim <- c(date.of.the.first.case-seed.estim[1], date.of.the.first.case-seed.estim[3], date.of.the.first.case-seed.estim[2])

date.max <- ymd(20200930)
times.max <- as.numeric(date.max - date.of.the.first.case)
times <- 0:times.max
all.times <- date.of.the.first.case + times

sim.susc <- NULL
sim.hosp <- NULL
sim.icu <- NULL
sim.deaths <- NULL
sim.deaths.daily <- NULL
sim.cases <- NULL
for(simulation.index in 1:no.bootstraps){
  parms.in <- fit.parms
  parms.in["R_0"] <- exp(sim.coefs$R_0[simulation.index])
  parms.in["seed"] <- exp(sim.coefs$seed[simulation.index])
  parms.in["kappa"] <- plogis(sim.coefs$kappa[simulation.index])
  sim <- sim.from.first.case(parms.in, times.max, inits)
  sim.susc <- cbind(sim.susc, sim$S)
  sim.hosp <- cbind(sim.hosp, sim$H)
  sim.icu <- cbind(sim.icu, sim$V)
  sim.deaths <- cbind(sim.deaths, sim$D)
  sim.deaths.daily <- cbind(sim.deaths.daily, diff(sim$D))
  sim.cases <- cbind(sim.cases, sim$IS)
}

sim.susc.ci <- apply(sim.susc, MAR = 1, FUN = quantile, probs = c(0.025, 0.975))
sim.hosp.ci <- apply(sim.hosp, MAR = 1, FUN = quantile, probs = c(0.025, 0.975))
sim.icu.ci <- apply(sim.icu, MAR = 1, FUN = quantile, probs = c(0.025, 0.975))
sim.deaths.ci <- apply(sim.deaths, MAR = 1, FUN = quantile, probs = c(0.025, 0.975))
sim.deaths.daily.ci <- apply(sim.deaths.daily, MAR = 1, FUN = quantile, probs = c(0.025, 0.975))
sim.cases.ci <- apply(sim.cases, MAR = 1, FUN = quantile, probs = c(0.025, 0.975))

sim.mean <- sim.from.first.case(fit.parms, times.max, inits)

df.susc <- data.frame(time = all.times, sim = sim.mean$S,
                            sim.lower = sim.susc.ci[1,], sim.upper = sim.susc.ci[2,])

df.hosp <- data.frame(time = all.times, sim = sim.mean$H,
                      sim.lower = sim.hosp.ci[1,], sim.upper = sim.hosp.ci[2,])

df.icu <- data.frame(time = all.times, sim = sim.mean$V,
                      sim.lower = sim.icu.ci[1,], sim.upper = sim.icu.ci[2,])

df.cum.deaths <- data.frame(time = all.times, sim = sim.mean$D,
                            sim.lower = sim.deaths.ci[1,], sim.upper = sim.deaths.ci[2,],
                            observed = c(reported$cum.deaths, rep(NA, length(all.times)-length(reported$cum.deaths))))

df.deaths <- data.frame(time = all.times[-1], sim = diff(sim.mean$D),
                        sim.lower = sim.deaths.daily.ci[1,], sim.upper = sim.deaths.daily.ci[2,],
                        observed = c(reported$inc.deaths[-1], rep(NA, length(all.times[-1])-length(reported$inc.deaths[-1]))))

################
## 5a. Plot R_t
################

time.week <- week(Rt.df$time)
time.week.unique <- unique(time.week)
time.breaks <- sapply(1:length(time.week.unique), function(k){
  this.date <- Rt.df$time[which(time.week.unique[k] == time.week)[1]]
  paste(year(this.date),month(this.date),day(this.date), sep = "-")
})
time.breaks <- ymd(time.breaks)
time.labels <- format(time.breaks, "%d/%m")

plot.rt <- ggplot(Rt.df, aes(x = time, y = Rt)) + geom_line(size = 2, col = brewer.pal(9, "Paired")[2])
plot.rt <- plot.rt + geom_ribbon(aes(ymin=Rt.min,ymax=Rt.max), alpha=0.3, fill = brewer.pal(9, "Paired")[2])
plot.rt <- plot.rt + scale_x_time(breaks = time.breaks, labels = time.labels)
plot.rt <- plot.rt + labs(x = "miesiąc 2020", y = "Efektywny współczynnik reprodukcji, R")


########################
## 5b. Plot projections
########################

times.months <- month(all.times)
times.months.unique <- unique(times.months)
time.breaks <- sapply(1:length(times.months.unique), function(k){
  this.date <- all.times[which(times.months.unique[k] == times.months)[1]]
  paste(year(this.date),month(this.date),day(this.date), sep = "-")
})
time.breaks <- ymd(time.breaks)
time.labels <- sapply(time.breaks, function(k) date2polish(k, return.only.month = T))

df.susc.prop <- df.susc
df.susc.prop$sim <- df.susc.prop$sim/popsize
df.susc.prop$sim.lower <- df.susc.prop$sim.lower/popsize
df.susc.prop$sim.upper <- df.susc.prop$sim.upper/popsize
plot.susceptibles <- ggplot(data = df.susc.prop, aes(x = time, y = sim)) + geom_line()
plot.susceptibles <- plot.susceptibles + scale_y_continuous(limits = c(0,1))
plot.susceptibles <- plot.susceptibles + geom_ribbon(aes(ymin=sim.lower,ymax=sim.upper), alpha=0.3)
plot.susceptibles <- plot.susceptibles + scale_x_time(breaks = time.breaks, labels = time.labels)
plot.susceptibles <- plot.susceptibles + labs(x = "miesiąc 2020", y = "Liczba osób podatnych")
# plot.susceptibles <- plot.susceptibles + geom_vline(xintercept = date.of.gov.restrictions, linetype = "dashed", col = "red")
# plot.susceptibles <- plot.susceptibles + geom_vline(xintercept = date.of.the.last.entry, linetype = "dashed", col = "black")

plot.hospitalised <- ggplot(data = df.hosp, aes(x = time, y = sim)) + geom_line(size = 2, col = brewer.pal(9, "Paired")[7])
plot.hospitalised <- plot.hospitalised + scale_y_log10(limits = c(1,NA))
plot.hospitalised <- plot.hospitalised + geom_ribbon(aes(ymin=sim.lower,ymax=sim.upper), alpha=0.3, fill = brewer.pal(9, "Paired")[7])
plot.hospitalised <- plot.hospitalised + scale_x_time(breaks = time.breaks, labels = time.labels)
plot.hospitalised <- plot.hospitalised + labs(x = "miesiąc 2020", y = "Liczba osób hospitalizowanych")

plot.icu <- ggplot(data = df.icu, aes(x = time, y = sim)) + geom_line(size = 2, col = brewer.pal(9, "Paired")[8])
plot.icu <- plot.icu + scale_y_log10(limits = c(1,NA))
plot.icu <- plot.icu + geom_ribbon(aes(ymin=sim.lower,ymax=sim.upper), alpha=0.3, fill = brewer.pal(9, "Paired")[8])
plot.icu <- plot.icu + scale_x_time(breaks = time.breaks, labels = time.labels)
plot.icu <- plot.icu + labs(x = "miesiąc 2020", y = "Liczba osób na intensywnej terapii")

plot.dead <- ggplot(df.deaths, aes(x = time, y = sim)) + geom_line(size = 1, col = brewer.pal(12, "Paired")[10])
plot.dead <- plot.dead + geom_point(aes(x = time, y = observed), col = "black", shape = 1)
plot.dead <- plot.dead + scale_y_log10(limits = c(1,NA))
plot.dead <- plot.dead + geom_ribbon(aes(ymin=sim.lower,ymax=sim.upper), alpha=0.3, fill = brewer.pal(12, "Paired")[10])
plot.dead <- plot.dead + scale_x_time(breaks = time.breaks, labels = time.labels)
plot.dead <- plot.dead + labs(x = "miesiąc 2020", y = "Dzienna liczba zgonów")
plot.dead <- plot.dead + geom_vline(xintercept = date.of.gov.restrictions, linetype = "dashed", col = "red")
plot.dead <- plot.dead + geom_vline(xintercept = date.of.the.last.entry, linetype = "dashed", col = "black")

plot.cum.dead <- ggplot(df.cum.deaths, aes(x = time, y = sim)) + geom_line(size = 1, col = brewer.pal(12, "Paired")[10])
plot.cum.dead <- plot.cum.dead + geom_point(aes(x = time, y = observed), col = "black", shape = 1)
plot.cum.dead <- plot.cum.dead + scale_y_log10(limits = c(1,NA))
plot.cum.dead <- plot.cum.dead + geom_ribbon(aes(ymin=sim.lower,ymax=sim.upper), alpha=0.3, fill = brewer.pal(12, "Paired")[10])
plot.cum.dead <- plot.cum.dead + scale_x_time(breaks = time.breaks, labels = time.labels)
plot.cum.dead <- plot.cum.dead + labs(x = "miesiąc 2020", y = "Całkowita liczba zgonów")
plot.cum.dead <- plot.cum.dead + geom_vline(xintercept = date.of.gov.restrictions, linetype = "dashed", col = "red")
plot.cum.dead <- plot.cum.dead + geom_vline(xintercept = date.of.the.last.entry, linetype = "dashed", col = "black")

plot.projections <- plot_grid(plot.hospitalised, plot.icu, plot.dead, plot.cum.dead, ncol = 2)
```

```{r, child=if (PL) 'version-PL/main-pl.Rmd'}
```

```{r, child=if (!PL) 'version-ENG/main-eng.Rmd'}
```

<!-- library(knitr) -->
<!-- library(markdown) -->
<!-- knit("master.Rmd") -->
<!-- markdownToHTML("master.md","/Users/rmostowy/GitHub/rmostowy.github.io/covid-19/projections-poland/index.html", fragment.only=TRUE) -->